name: Java and Maven Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/checkout@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test with Maven
        run: mvn test
      
      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-output
          path: ExtentReport.html
